# Generated by Django 5.2.13 on 2026-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_origem', models.IntegerField(verbose_name='ano de origem')),
                ('codigo_origem', models.CharField(max_length=64, verbose_name='código de origem')),
                ('descricao_origem', models.CharField(max_length=512, verbose_name='descrição de origem')),
                ('ano_destino', models.IntegerField(verbose_name='ano de destino')),
                ('codigo_destino', models.CharField(max_length=64, verbose_name='código de destino')),
            ],
            options={
                'verbose_name': 'mapeamento de item',
                'verbose_name_plural': 'mapeamentos de itens',
                'ordering': ('ano_origem', 'codigo_origem'),
            },
        ),
    ]
