# Generated by Django 5.2.13 on 2026-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pncp_id', models.CharField(max_length=64, unique=True)),
                ('orgao_cnpj', models.CharField(db_index=True, max_length=14)),
                ('ano', models.IntegerField(db_index=True)),
                ('sequencial', models.IntegerField()),
                ('modalidade_id', models.IntegerField()),
                ('modalidade_nome', models.CharField(blank=True, default='', max_length=120)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('objeto', models.TextField(blank=True, default='')),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'ordering': ('-ano', 'sequencial'),
                'unique_together': {('orgao_cnpj', 'ano', 'sequencial')},
            },
        ),
    ]
