# Generated by Django 5.2.13 on 2026-04-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dashboard.compra')),
            ],
            options={
                'ordering': ('numero_item',),
                'unique_together': {('compra', 'numero_item')},
            },
        ),
    ]
