# Generated by Django 5.2.13 on 2026-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='cnpj_vencedor',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='marca_vencedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='nome_vencedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='valor_unitario_homologado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
