# Generated by Django 5.2.13 on 2026-04-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_itemcompra_cnpj_vencedor_itemcompra_marca_vencedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_padrao', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=120, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome_padrao',),
            },
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='produto_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vinculados', to='dashboard.produtocatalogo'),
        ),
    ]
