# Generated by Django 5.2.13 on 2026-04-10 18:22

from django.db import migrations

from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_produtocatalogo_itemcompra_produto_master"),
    ]

    operations = [
        VectorExtension(),
    ]
