# Generated by Django 5.2.13 on 2026-04-10 18:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_enable_pgvector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocatalogo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
