# Generated by Django 5.2.13 on 2026-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_produtocatalogo_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_cnpj', models.CharField(db_index=True, max_length=14)),
                ('ano', models.IntegerField(db_index=True)),
                ('ultimo_sequencial_completo', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-ano', 'orgao_cnpj'),
                'unique_together': {('orgao_cnpj', 'ano')},
            },
        ),
    ]
